import { ChakraProviders } from "@/components/ChakraProviders";
import {Layout} from "@/components/Layout";
import { NextAuthProvider } from "@/components/NextauthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
      <ChakraProviders>
        <Layout>
        {children}
        </Layout>
      </ChakraProviders>
      </NextAuthProvider>
      </body>
    </html>
  );
}
